In [3]:
import pymysql
import pandas as pd
import tqdm as tqdm
from my_utils import *

In [4]:

#실행전 주의사항 : 본인의 파이참 or my_utils파일을 확인한다.

# 1. 빈행을 삭제한다

# 2. 각 칼럼당 같은 값이 10개 가 아닌경우 그 데이터값을 전부 삭제 

# 3. 전처리 완료//

column_list = ['gameId', 'gameDuration', 'gameVersion', 'summonerName', 'summonerLevel', 'participantId','championName', 'champLevel', 'champExperience', 
               'teamPosition', 'teamId','ban', 'firstpurchased', 'win', 'gameEndedInEarlySurrender', 'firstBloodKill','doubleKills','tripleKills','quadraKills',
               'pentaKills', 'kills', 'deaths', 'assists','kda','totalDamageDealtToChampions', 'totalDamageTaken']


conn = connect_mysql()

# 전체 데이터 중에서 빈칸을 전부다 삭제
for i in range(len(column_list)):
    sql = (
            f"select * from lol_datas where {column_list[i]} = ''"
        )
    print(sql)
    result = sql_execute(conn,sql)

    print("빈칸이 있는 데이터의 수는 총 {}개 입니다.".format(len(result)))
    
    if result != '' :
        for j in range(len(result)):
          
            sql1 = (f"delete from lol_datas where gameId = \'{result[j][1]}\'")
            sql_execute(conn,sql1)
        print("삭제 완료된 데이터의 수는 총 {}개 입니다.".format(len(result)))


# Gameid가 10개가 아닌 게임번호를 삭제
sql3 = (
        f"select gameId, count(gameId)  from lol_datas group by gameId having count(gameId) != 10 "    
        )

result = sql_execute(conn,sql3)

print("칼럼이 10개단위가 아닌 데이터의 수는 총 {}개 입니다.".format(len(result)))
for i in range(len(result)):
    print(result[i][0])
    sql2 = (
        f"delete from lol_datas where gameId = \'{result[i][0]}\'"
        )
    sql_execute(conn,sql2)

conn.commit()

print("삭제 완료되었습니다.")
conn.close()

#mysql에서 먼저 전처리를 실행시켜주어 데이터를 사용함에 있어서 문제가 없게 만듦

select * from lol_datas where gameId = ''
빈칸이 있는 데이터의 수는 총 0개 입니다.
삭제 완료된 데이터의 수는 총 0개 입니다.
select * from lol_datas where gameDuration = ''
빈칸이 있는 데이터의 수는 총 0개 입니다.
삭제 완료된 데이터의 수는 총 0개 입니다.
select * from lol_datas where gameVersion = ''
빈칸이 있는 데이터의 수는 총 0개 입니다.
삭제 완료된 데이터의 수는 총 0개 입니다.
select * from lol_datas where summonerName = ''
빈칸이 있는 데이터의 수는 총 1465개 입니다.
삭제 완료된 데이터의 수는 총 1465개 입니다.
select * from lol_datas where summonerLevel = ''
빈칸이 있는 데이터의 수는 총 0개 입니다.
삭제 완료된 데이터의 수는 총 0개 입니다.
select * from lol_datas where participantId = ''
빈칸이 있는 데이터의 수는 총 0개 입니다.
삭제 완료된 데이터의 수는 총 0개 입니다.
select * from lol_datas where championName = ''
빈칸이 있는 데이터의 수는 총 0개 입니다.
삭제 완료된 데이터의 수는 총 0개 입니다.
select * from lol_datas where champLevel = ''
빈칸이 있는 데이터의 수는 총 0개 입니다.
삭제 완료된 데이터의 수는 총 0개 입니다.
select * from lol_datas where champExperience = ''
빈칸이 있는 데이터의 수는 총 3개 입니다.
삭제 완료된 데이터의 수는 총 3개 입니다.
select * from lol_datas where teamPosition = ''
빈칸이 있는 데이터의 수는 총 13개 입니다.
삭제 완료된 데이터의 수는 총 13개 입니다.
select * from lol_datas where teamId = ''
빈칸이 있는 데이터의 수는 총 0개 입니다.
삭제 완료된 데이터의 수는 총 0개 입니다.
select * from lol_datas where ban = ''
빈칸이 있는 데이터의 수는 총 0개 입니다.
삭제 완료된 데이터의 수는 총 0개 입니다.
select * from lol_datas where firstpurchased = ''
빈칸이 있는 데이터의 수는 총 0개 입니다.
삭제 완료된 데이터의 수는 총 0개 입니다.
select * from lol_datas where win = ''
빈칸이 있는 데이터의 수는 총 0개 입니다.
삭제 완료된 데이터의 수는 총 0개 입니다.
select * from lol_datas where gameEndedInEarlySurrender = ''
빈칸이 있는 데이터의 수는 총 0개 입니다.
삭제 완료된 데이터의 수는 총 0개 입니다.
select * from lol_datas where firstBloodKill = ''
빈칸이 있는 데이터의 수는 총 0개 입니다.
삭제 완료된 데이터의 수는 총 0개 입니다.
select * from lol_datas where doubleKills = ''
빈칸이 있는 데이터의 수는 총 0개 입니다.
삭제 완료된 데이터의 수는 총 0개 입니다.
select * from lol_datas where tripleKills = ''
빈칸이 있는 데이터의 수는 총 0개 입니다.
삭제 완료된 데이터의 수는 총 0개 입니다.
select * from lol_datas where quadraKills = ''
빈칸이 있는 데이터의 수는 총 0개 입니다.
삭제 완료된 데이터의 수는 총 0개 입니다.
select * from lol_datas where pentaKills = ''
빈칸이 있는 데이터의 수는 총 0개 입니다.
삭제 완료된 데이터의 수는 총 0개 입니다.
select * from lol_datas where kills = ''
빈칸이 있는 데이터의 수는 총 25510개 입니다.
삭제 완료된 데이터의 수는 총 25510개 입니다.
select * from lol_datas where deaths = ''
빈칸이 있는 데이터의 수는 총 1901개 입니다.
삭제 완료된 데이터의 수는 총 1901개 입니다.
select * from lol_datas where assists = ''
빈칸이 있는 데이터의 수는 총 2577개 입니다.
삭제 완료된 데이터의 수는 총 2577개 입니다.
select * from lol_datas where kda = ''
빈칸이 있는 데이터의 수는 총 0개 입니다.
삭제 완료된 데이터의 수는 총 0개 입니다.
select * from lol_datas where totalDamageDealtToChampions = ''
빈칸이 있는 데이터의 수는 총 0개 입니다.
삭제 완료된 데이터의 수는 총 0개 입니다.
select * from lol_datas where totalDamageTaken = ''
빈칸이 있는 데이터의 수는 총 0개 입니다.
삭제 완료된 데이터의 수는 총 0개 입니다.
칼럼이 10개단위가 아닌 데이터의 수는 총 0개 입니다.
삭제 완료되었습니다.